//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapsEval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddsForEval_0623Companies
    {
        public Nullable<int> AddressID { get; set; }
        public string Address { get; set; }
        public Nullable<double> AddressLatitude { get; set; }
        public Nullable<double> AddressLongitude { get; set; }
        public string IC { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderingWeight { get; set; }
        public string TurnovCatFinancialsSSO { get; set; }
        public string NACELabelSK { get; set; }
    
        public virtual AddsForEval_0623 AddsForEval_0623 { get; set; }
    }
}
